version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    container_name: "caddy"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/volumes/caddy:/data
      - ${CADDYFILE:-./nginx/Caddyfile}:/etc/caddy/Caddyfile
      - ~/volumes/.lnd:/lnd:ro
      - ~/volumes/.lnd2:/lnd2:ro
      - ~/volumes/.lnd3:/lnd3:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      SUBDOMAIN: $SUBDOMAIN
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  bitcoind:
    container_name: "bitcoind"
    build: .
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    volumes:
      - ~/volumes/.bitcoin:/root/.bitcoin
    environment:
      UACOMMENT: $UACOMMENT
      BLOCKPRODUCTIONDELAY: $BLOCKPRODUCTIONDELAY
      NBITS: $NBITS
      RPCPASSWORD: $RPCPASSWORD
      PRIVKEY: $PRIVKEY
      SIGNETCHALLENGE: $SIGNETCHALLENGE
      EXTERNAL_IP: $EXTERNAL_IP
      MINERENABLED: $MINERENABLED
      ADDNODE: $ADDNODE
      MINE_GENESIS: $MINE_GENESIS
      ADDR: $ADDR
    ports:
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "38332:38332"
      - "38333:38333"
      - "38334:38334"

  rgs_server:
    container_name: "rgs_server"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    build:
      context: ./rapid-gossip-sync-server
      dockerfile: ./docker/Dockerfile.rgs
    volumes:
      - ~/volumes/rgs:/usr/src/app:cached
    links:
      - postgres
      - bitcoind
    depends_on:
      - postgres
    environment:
      RAPID_GOSSIP_SYNC_SERVER_DB_HOST: postgres
      RAPID_GOSSIP_SYNC_SERVER_DB_USER: postgres
      RAPID_GOSSIP_SYNC_SERVER_DB_PASSWORD: docker
      RAPID_GOSSIP_SYNC_SERVER_DB_NAME: pgdb
      RAPID_GOSSIP_SYNC_SERVER_NETWORK: signet
      RAPID_GOSSIP_SYNC_SERVER_SNAPSHOT_INTERVAL: 10800 # 3 hours
      BITCOIN_REST_DOMAIN: bitcoind
      BITCOIN_REST_PORT: 38332
      LN_PEERS: $LND_PUBKEY@lnd:9735 # lnd's node id
    entrypoint: ["rapid-gossip-sync-server"]

  rgs_files:
    image: joseluisq/static-web-server:2
    restart: on-failure
    container_name: rgs_files
    volumes:
      - /home/ubuntu/volumes/rgs:/public
      - /home/ubuntu/mutiny-net/nginx/rgs.toml:/config.toml
    ports:
      - 8000:80

  postgres:
    container_name: "postgres"
    image: "postgres:12-alpine"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    user: "0:1000"
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pgdb

  electrs:
    container_name: "electrs"
    build:
      context: ./electrs
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    environment:
      FLAGS: "-vvvv --signet-magic $SIGNET_MAGIC --jsonrpc-import --daemon-dir /root/.bitcoin/signet --daemon-rpc-addr bitcoind:38332 --timestamp --blocks-dir /root/.bitcoin/signet/blocks --cookie=bitcoin:$RPCPASSWORD --db-dir /root/.electrs --network signet --electrum-rpc-addr 0.0.0.0:50001 --http-addr 0.0.0.0:3003"
    volumes:
      - ~/volumes/electrs:/root/.electrs
    ports:
      - "3003:3003"
      - "50001:50001"

  mempool_web:
    container_name: "mempool_web"
    environment:
      MAINNET_ENABLED: "false"
      ROOT_NETWORK: "signet"
      FRONTEND_HTTP_PORT: "8888"
      BACKEND_MAINNET_HTTP_HOST: "mempool_api"
      LIGHTNING: "true"
    image: mempool/frontend:latest
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    command: "./wait-for mempool_db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8888:8888"

  mempool_api:
    container_name: "mempool_api"
    environment:
      MEMPOOL_NETWORK: "signet"
      MEMPOOL_BACKEND: "none"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      ESPLORA_REST_API_URL: "http://electrs:3003"
      CORE_RPC_HOST: "bitcoind"
      CORE_RPC_PORT: "38332"
      CORE_RPC_USERNAME: "bitcoin"
      CORE_RPC_PASSWORD: $RPCPASSWORD
      CORE_RPC_TIMEOUT: "60000"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "false"
      LIGHTNING_ENABLED: "true"
      LIGHTNING_BACKEND: "lnd"
      LND_TLS_CERT_PATH: "/root/.lnd/tls.cert"
      LND_MACAROON_PATH: "/root/.lnd/data/chain/bitcoin/signet/admin.macaroon"
      LND_REST_API_URL: "https://lnd:8081"
    image: mempool/backend:latest
    logging: *default-logging
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool_db:3306 --timeout=720 --strict -- ./start.sh"
    ports:
      - "8889:8889"
      - "8999:8999"
    volumes:
      - ~/volumes/mempool:/backend/cache
      - ~/volumes/.lnd:/root/.lnd:ro

  mempool_db:
    container_name: "mempool_db"
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    logging: *default-logging
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ~/volumes/mysql/data:/var/lib/mysql

  thunderhub:
    image: ghcr.io/evanfeenstra/thunderhub:latest
    logging: *default-logging
    container_name: "thunderhub"
    restart: always
    volumes:
      - ./nginx/thunderhub.yaml:/data/thunderhub.yaml
      - ./nginx/thub.env:/app/.env.local
      - ~/volumes/.lnd:/lnd:ro
      - ~/volumes/.lnd2:/lnd2:ro
      - ~/volumes/.lnd3:/lnd3:ro

  vss:
    build:
      context: ./vss-rs
      dockerfile: Dockerfile
    container_name: "vss"
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: on-failure
    stop_signal: SIGINT
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      DATABASE_URL: postgres://postgres:docker@postgres/pgdb
      SELF_HOST: "true"
      RUST_LOG: "info"

  lnd:
    container_name: "lnd"
    image: lightninglabs/lnd:v0.18.2-beta
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 10m
    environment:
      RPCPASSWORD: $RPCPASSWORD
    command:
      [
        "--bitcoin.active",
        "--bitcoin.signet",
        "--bitcoin.node=bitcoind",
        "--maxpendingchannels=100000",
        "--rpclisten=0.0.0.0:10009",
        "--restlisten=0.0.0.0:8081",
        "--bitcoind.rpchost=bitcoind:38332",
        "--bitcoind.rpcuser=bitcoin",
        "--bitcoind.rpcpass=$RPCPASSWORD",
        "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332",
        "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333",
        "--db.bolt.auto-compact",
        "--db.prune-revocation",
        "--alias=${LND_ALIAS:-Portal Faucet LND}",
        "--tlsextradomain=lp1.$SUBDOMAIN",
        "--tlsextradomain=lnd.$SUBDOMAIN",
        "--tlsextradomain=lnd",
        "--protocol.option-scid-alias",
        "--protocol.wumbo-channels",
        "--accept-keysend",
        "--minchansize=25000",
        "--noseedbackup",
        "--gc-canceled-invoices-on-startup",
        "--coin-selection-strategy=random",
        "--protocol.custom-message=513",
        "--protocol.custom-nodeann=39",
        "--protocol.custom-init=39",
        "--reset-wallet-transactions",
      ]
    volumes:
      - ~/volumes/.lnd:/root/.lnd
    ports:
      - "9735:9735"
      - "10009:10009"
      - "8081:8081"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  lnd2:
    container_name: "lnd2"
    image: lightninglabs/lnd:v0.18.2-beta
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 10m
    environment:
      RPCPASSWORD: $RPCPASSWORD
    command:
      [
        "--bitcoin.active",
        "--bitcoin.signet",
        "--bitcoin.node=bitcoind",
        "--maxpendingchannels=100000",
        "--listen=:9736",
        "--rpclisten=0.0.0.0:10010",
        "--restlisten=0.0.0.0:8082",
        "--bitcoind.rpchost=bitcoind:38332",
        "--bitcoind.rpcuser=bitcoin",
        "--bitcoind.rpcpass=$RPCPASSWORD",
        "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332",
        "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333",
        "--db.bolt.auto-compact",
        "--db.prune-revocation",
        "--alias=${LND_ALIAS:-Portal Faucet LND 2}",
        "--tlsextradomain=lp2.$SUBDOMAIN",
        "--tlsextradomain=lnd2.$SUBDOMAIN",
        "--tlsextradomain=lnd2",
        "--protocol.option-scid-alias",
        "--protocol.wumbo-channels",
        "--accept-keysend",
        "--minchansize=25000",
        "--noseedbackup",
        "--gc-canceled-invoices-on-startup",
        "--coin-selection-strategy=random",
        "--protocol.custom-message=513",
        "--protocol.custom-nodeann=39",
        "--protocol.custom-init=39",
        "--reset-wallet-transactions",
      ]
    volumes:
      - ~/volumes/.lnd2:/root/.lnd
    ports:
      - "9736:9736"
      - "10010:10010"
      - "8082:8082"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  lnd3:
    container_name: "lnd3"
    image: lightninglabs/lnd:v0.18.2-beta
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 10m
    environment:
      RPCPASSWORD: $RPCPASSWORD
    command:
      [
        "--bitcoin.active",
        "--bitcoin.signet",
        "--bitcoin.node=bitcoind",
        "--maxpendingchannels=100000",
        "--listen=:9737",
        "--rpclisten=0.0.0.0:10011",
        "--restlisten=0.0.0.0:8083",
        "--bitcoind.rpchost=bitcoind:38332",
        "--bitcoind.rpcuser=bitcoin",
        "--bitcoind.rpcpass=$RPCPASSWORD",
        "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332",
        "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333",
        "--db.bolt.auto-compact",
        "--db.prune-revocation",
        "--alias=${LND_ALIAS:-Portal Faucet LND 3}",
        "--tlsextradomain=lp3.$SUBDOMAIN",
        "--tlsextradomain=lnd3.$SUBDOMAIN",
        "--tlsextradomain=lnd3",
        "--protocol.option-scid-alias",
        "--protocol.wumbo-channels",
        "--accept-keysend",
        "--minchansize=25000",
        "--noseedbackup",
        "--gc-canceled-invoices-on-startup",
        "--coin-selection-strategy=random",
        "--protocol.custom-message=513",
        "--protocol.custom-nodeann=39",
        "--protocol.custom-init=39",
        "--reset-wallet-transactions",
      ]
    volumes:
      - ~/volumes/.lnd3:/root/.lnd
    ports:
      - "9737:9737"
      - "10011:10011"
      - "8083:8083"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
