[general]

cors-allow-origins = "*"

log-level = "debug"

cache-control-headers = false

[advanced]

[[advanced.rewrites]]
source = "/snapshot/{*}.bin"
destination = "/res/symlinks/$1.bin"

[[advanced.rewrites]]
source = "/snapshot/{*}"
destination = "/res/symlinks/$1.bin"
